### ISSUE TITLE
请问:TCP连接的和demo里UDP的差别在哪? 

### ISSUE THREAD

**Issue by zhd571996497** [cgcym1234/YYVPN#1]

**Comment by cgcym1234** [comment]
再看看Demo里的流程：
1.从App抓到的是IP层的数据包
2.把上面IP层的数据包二进制数据，再通过UDP方式发送给代理服务器，就和发送普通数据一样
当然上面也可以使用TCP方式，差别的话其实就是使用TCP和UDP的区别呗。。
